import type { Centre, Farmer, Notification, ProcurementRequest } from "./types";

export const DEMO_FARMER_ID = "KSN1024";

export const demoFarmers: Farmer[] = [
  { id: "f1", name: "Rajesh Kumar", mobile: "98XXXXXX21", village: "Rampur", farmerId: "KSN1024" },
  { id: "f2", name: "Sunita Devi", mobile: "97XXXXXX08", village: "Bhojpur", farmerId: "KSN1025" },
  { id: "f3", name: "Rahul Kumar", mobile: "99XXXXXX44", village: "Rampur", farmerId: "KSN1026" },
  { id: "f4", name: "Mahesh Yadav", mobile: "96XXXXXX72", village: "Sitapur", farmerId: "KSN1027" },
  { id: "f5", name: "Anita Sharma", mobile: "93XXXXXX15", village: "Kheri", farmerId: "KSN1028" },
  { id: "f6", name: "Devendra Singh", mobile: "90XXXXXX33", village: "Bansi", farmerId: "KSN1029" },
];

export const demoCentres: Centre[] = [
  {
    id: "c1",
    name: "XYZ Procurement Centre",
    location: "Delhi",
    capacity: 200,
    queue: 24,
    availableSlots: 8,
    status: "Open",
  },
  {
    id: "c2",
    name: "Rampur Mandi Centre",
    location: "Rampur, Uttar Pradesh",
    capacity: 150,
    queue: 61,
    availableSlots: 3,
    status: "Almost Full",
  },
  {
    id: "c3",
    name: "Sitapur Kisan Kendra",
    location: "Sitapur, Uttar Pradesh",
    capacity: 180,
    queue: 12,
    availableSlots: 11,
    status: "Open",
  },
  {
    id: "c4",
    name: "Bhojpur Grain Depot",
    location: "Bhojpur, Bihar",
    capacity: 120,
    queue: 118,
    availableSlots: 0,
    status: "Closed",
  },
];

const now = "2026-09-07T09:30:00.000Z";

export const demoRequests: ProcurementRequest[] = [
  {
    requestId: "REQ-1001",
    farmerId: "KSN1024",
    farmerName: "Rajesh Kumar",
    crop: "Wheat",
    quantity: 250,
    centre: "XYZ Procurement Centre",
    date: "2026-09-12",
    token: "A104",
    slot: "10:00 AM – 11:00 AM",
    status: "REACHED_CENTRE",
    createdAt: now,
    updatedAt: now,
  },
  {
    requestId: "REQ-1002",
    farmerId: "KSN1024",
    farmerName: "Rajesh Kumar",
    crop: "Paddy (Rice)",
    quantity: 400,
    actualWeight: 392,
    centre: "Rampur Mandi Centre",
    date: "2026-08-28",
    token: "A088",
    slot: "11:00 AM – 12:00 PM",
    status: "PAYMENT_INITIATED",
    verification: ["Farmer Identity", "Land / Farmer Documents", "Crop Details", "Token", "Weight Details"],
    createdAt: "2026-08-28T05:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
  },
  {
    requestId: "REQ-1003",
    farmerId: "KSN1025",
    farmerName: "Sunita Devi",
    crop: "Wheat",
    quantity: 180,
    centre: "XYZ Procurement Centre",
    date: "2026-09-12",
    token: "A105",
    slot: "11:00 AM – 12:00 PM",
    status: "SLOT_ASSIGNED",
    createdAt: now,
    updatedAt: now,
  },
  {
    requestId: "REQ-1004",
    farmerId: "KSN1026",
    farmerName: "Rahul Kumar",
    crop: "Maize",
    quantity: 320,
    actualWeight: 318,
    centre: "XYZ Procurement Centre",
    date: "2026-09-12",
    token: "A106",
    slot: "12:00 PM – 1:00 PM",
    status: "WEIGHING",
    createdAt: now,
    updatedAt: now,
  },
  {
    requestId: "REQ-1005",
    farmerId: "KSN1027",
    farmerName: "Mahesh Yadav",
    crop: "Gram (Chana)",
    quantity: 150,
    centre: "Sitapur Kisan Kendra",
    date: "2026-09-12",
    token: "A107",
    slot: "2:00 PM – 3:00 PM",
    status: "TOKEN_GENERATED",
    createdAt: now,
    updatedAt: now,
  },
  {
    requestId: "REQ-1006",
    farmerId: "KSN1028",
    farmerName: "Anita Sharma",
    crop: "Mustard",
    quantity: 210,
    actualWeight: 205,
    centre: "Rampur Mandi Centre",
    date: "2026-09-11",
    token: "A103",
    slot: "10:00 AM – 11:00 AM",
    status: "COMPLETED",
    verification: ["Farmer Identity", "Land / Farmer Documents", "Crop Details", "Token", "Weight Details"],
    createdAt: "2026-09-11T05:00:00.000Z",
    updatedAt: "2026-09-11T08:20:00.000Z",
  },
  {
    requestId: "REQ-1007",
    farmerId: "KSN1029",
    farmerName: "Devendra Singh",
    crop: "Bajra",
    quantity: 275,
    centre: "Sitapur Kisan Kendra",
    date: "2026-09-13",
    token: "A108",
    slot: "3:00 PM – 4:00 PM",
    status: "REQUESTED",
    createdAt: now,
    updatedAt: now,
  },
  {
    requestId: "REQ-1008",
    farmerId: "KSN1025",
    farmerName: "Sunita Devi",
    crop: "Wheat",
    quantity: 300,
    actualWeight: 296,
    centre: "XYZ Procurement Centre",
    date: "2026-09-05",
    token: "A095",
    slot: "12:00 PM – 1:00 PM",
    status: "PAYMENT_INITIATED",
    verification: ["Farmer Identity", "Land / Farmer Documents", "Crop Details", "Token", "Weight Details"],
    createdAt: "2026-09-05T05:00:00.000Z",
    updatedAt: "2026-09-05T10:00:00.000Z",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "n1",
    farmerId: "KSN1024",
    title: "Token generated",
    message: "Your token A104 has been generated for XYZ Procurement Centre.",
    kind: "token",
    createdAt: "2026-09-07T04:10:00.000Z",
    read: false,
  },
  {
    id: "n2",
    farmerId: "KSN1024",
    title: "Slot confirmed",
    message: "Your procurement slot is confirmed for 10:00 AM – 11:00 AM on 12 September 2026.",
    kind: "slot",
    createdAt: "2026-09-07T04:12:00.000Z",
    read: false,
  },
  {
    id: "n3",
    farmerId: "KSN1024",
    title: "Token scanned",
    message: "Your token A104 has been scanned at the procurement centre.",
    kind: "scan",
    createdAt: "2026-09-07T09:30:00.000Z",
    read: false,
  },
  {
    id: "n4",
    farmerId: "KSN1024",
    title: "Payment initiated",
    message: "Procurement completed for token A088. Payment initiated to your bank account.",
    kind: "payment",
    createdAt: "2026-08-28T09:05:00.000Z",
    read: true,
  },
];

export const dailyProcurement = [
  { day: "Mon", quantity: 1820 },
  { day: "Tue", quantity: 2140 },
  { day: "Wed", quantity: 1650 },
  { day: "Thu", quantity: 2480 },
  { day: "Fri", quantity: 2910 },
  { day: "Sat", quantity: 2260 },
  { day: "Sun", quantity: 980 },
];
