/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CentresRouteImport } from './routes/centres'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer.notifications'
import { Route as FarmerRequestRouteImport } from './routes/farmer.request'
import { Route as FarmerScheduleRouteImport } from './routes/farmer.schedule'
import { Route as FarmerTrackRouteImport } from './routes/farmer.track'
import { Route as LoginFarmerRouteImport } from './routes/login.farmer'
import { Route as LoginOfficerRouteImport } from './routes/login.officer'
import { Route as FarmerTokenTokenRouteImport } from './routes/farmer.token.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoute = CentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerRequestRoute = FarmerRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerScheduleRoute = FarmerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerTrackRoute = FarmerTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => FarmerRoute,
} as any)
const LoginFarmerRoute = LoginFarmerRouteImport.update({
  id: '/login/farmer',
  path: '/login/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOfficerRoute = LoginOfficerRouteImport.update({
  id: '/login/officer',
  path: '/login/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerTokenTokenRoute = FarmerTokenTokenRouteImport.update({
  id: '/token/$token',
  path: '/token/$token',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/centres': typeof CentresRoute
  '/contact': typeof ContactRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/request': typeof FarmerRequestRoute
  '/farmer/schedule': typeof FarmerScheduleRoute
  '/farmer/track': typeof FarmerTrackRoute
  '/login/farmer': typeof LoginFarmerRoute
  '/login/officer': typeof LoginOfficerRoute
  '/farmer/': typeof FarmerIndexRoute
  '/farmer/token/$token': typeof FarmerTokenTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/centres': typeof CentresRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/request': typeof FarmerRequestRoute
  '/farmer/schedule': typeof FarmerScheduleRoute
  '/farmer/track': typeof FarmerTrackRoute
  '/login/farmer': typeof LoginFarmerRoute
  '/login/officer': typeof LoginOfficerRoute
  '/farmer': typeof FarmerIndexRoute
  '/farmer/token/$token': typeof FarmerTokenTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/centres': typeof CentresRoute
  '/contact': typeof ContactRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/request': typeof FarmerRequestRoute
  '/farmer/schedule': typeof FarmerScheduleRoute
  '/farmer/track': typeof FarmerTrackRoute
  '/login/farmer': typeof LoginFarmerRoute
  '/login/officer': typeof LoginOfficerRoute
  '/farmer/': typeof FarmerIndexRoute
  '/farmer/token/$token': typeof FarmerTokenTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/centres'
    | '/contact'
    | '/farmer'
    | '/how-it-works'
    | '/farmer/notifications'
    | '/farmer/request'
    | '/farmer/schedule'
    | '/farmer/track'
    | '/login/farmer'
    | '/login/officer'
    | '/farmer/'
    | '/farmer/token/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/centres'
    | '/contact'
    | '/how-it-works'
    | '/farmer/notifications'
    | '/farmer/request'
    | '/farmer/schedule'
    | '/farmer/track'
    | '/login/farmer'
    | '/login/officer'
    | '/farmer'
    | '/farmer/token/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/centres'
    | '/contact'
    | '/farmer'
    | '/how-it-works'
    | '/farmer/notifications'
    | '/farmer/request'
    | '/farmer/schedule'
    | '/farmer/track'
    | '/login/farmer'
    | '/login/officer'
    | '/farmer/'
    | '/farmer/token/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CentresRoute: typeof CentresRoute
  ContactRoute: typeof ContactRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginFarmerRoute: typeof LoginFarmerRoute
  LoginOfficerRoute: typeof LoginOfficerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres': {
      id: '/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof CentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/request': {
      id: '/farmer/request'
      path: '/request'
      fullPath: '/farmer/request'
      preLoaderRoute: typeof FarmerRequestRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/schedule': {
      id: '/farmer/schedule'
      path: '/schedule'
      fullPath: '/farmer/schedule'
      preLoaderRoute: typeof FarmerScheduleRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/track': {
      id: '/farmer/track'
      path: '/track'
      fullPath: '/farmer/track'
      preLoaderRoute: typeof FarmerTrackRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/login/farmer': {
      id: '/login/farmer'
      path: '/login/farmer'
      fullPath: '/login/farmer'
      preLoaderRoute: typeof LoginFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/officer': {
      id: '/login/officer'
      path: '/login/officer'
      fullPath: '/login/officer'
      preLoaderRoute: typeof LoginOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/token/$token': {
      id: '/farmer/token/$token'
      path: '/token/$token'
      fullPath: '/farmer/token/$token'
      preLoaderRoute: typeof FarmerTokenTokenRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerRequestRoute: typeof FarmerRequestRoute
  FarmerScheduleRoute: typeof FarmerScheduleRoute
  FarmerTrackRoute: typeof FarmerTrackRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  FarmerTokenTokenRoute: typeof FarmerTokenTokenRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerRequestRoute: FarmerRequestRoute,
  FarmerScheduleRoute: FarmerScheduleRoute,
  FarmerTrackRoute: FarmerTrackRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  FarmerTokenTokenRoute: FarmerTokenTokenRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CentresRoute: CentresRoute,
  ContactRoute: ContactRoute,
  FarmerRoute: FarmerRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginFarmerRoute: LoginFarmerRoute,
  LoginOfficerRoute: LoginOfficerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
